# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewStartScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
# import gui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        #set the background color of the window to black
        MainWindow.setStyleSheet("background-color: #16161a;")
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(120, 248, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 248, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 39, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(0, 10, 801, 121))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setBold(False)
        font.setWeight(50)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.Start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Button.setGeometry(QtCore.QRect(290, 390, 231, 81))
        self.Start_Button.setStyleSheet("font: 87 18pt \"Nunito Black\";\n"
"color: #78ffc0;\n")
        self.Start_Button.setObjectName("Start_Button")
        self.Skill_Counter = QtWidgets.QLabel(self.centralwidget)
        self.Skill_Counter.setGeometry(QtCore.QRect(0, 140, 801, 181))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setBold(False)
        font.setWeight(50)
        self.Skill_Counter.setFont(font)
        self.Skill_Counter.setObjectName("Skill_Counter")
        self.Difficulty_Label = QtWidgets.QLabel(self.centralwidget)
        self.Difficulty_Label.setGeometry(QtCore.QRect(0, 230, 801, 121))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.Difficulty_Label.setFont(font)
        self.Difficulty_Label.setObjectName("Difficulty_Label")
        #set the bg color of the label to transparent
        self.Difficulty_Label.setStyleSheet("background-color: transparent;")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 200, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(120, 248, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 200, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(120, 248, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(230, 320, 341, 20))
        self.horizontalSlider.setMaximum(20)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 20)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; color:#78ffc0;\">Checkmate!</span></p></body></html>"))
        self.Start_Button.setText(_translate("MainWindow", "Start"))
        self.Skill_Counter.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; color:#78f8ff;\">20</span></p></body></html>"))
        self.Difficulty_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#78f8ff;\">Grandmaster</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "→"))
        self.pushButton_2.setText(_translate("MainWindow", "←"))

_translate = QtCore.QCoreApplication.translate
SkillLevel = 20
SkillLabels = [
    "Newbie",
    "Newbie",
    "Beginner",
    "Beginner",
    "Easy",
    "Easy",
    "Amature",
    "Amature",
    "Standard",
    "Standard",
    "Intermediate",
    "Intermediate",
    "Advanced",
    "Advanced",
    "Expert",
    "Expert",
    "Master",
    "Master",
    "Grandmaster",
    "Grandmaster"
]
#region Functions
def OnSliderChange(value):
    global SkillLevel
    SkillLevel = value
    ui.Skill_Counter.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; color:#78f8ff;\">"+str(value)+"</span></p></body></html>"))
    ui.Difficulty_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#78f8ff;\">"+SkillLabels[value-1]+"</span></p></body></html>"))
def IncreaseSkill():
    global SkillLevel
    SkillLevel += 1
    if(SkillLevel > 20):
        SkillLevel = 20
    ui.horizontalSlider.setValue(SkillLevel)
    OnSliderChange(SkillLevel)
def DecreaseSkill():
    global SkillLevel 
    SkillLevel -= 1
    if(SkillLevel < 1):
        SkillLevel = 1
    ui.horizontalSlider.setValue(SkillLevel)
    OnSliderChange(SkillLevel)
def StartGame():
    global SkillLevel
    import gui
    gui.Start(SkillLevel)
    MainWindow.close()
    # gui.Start(SkillLevel)

#endregion
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
ui.horizontalSlider.valueChanged.connect(OnSliderChange)
ui.pushButton.clicked.connect(IncreaseSkill)
ui.pushButton_2.clicked.connect(DecreaseSkill)
ui.Start_Button.clicked.connect(StartGame)
#Set the mainwindow to fullscreen
MainWindow.showFullScreen()
sys.exit(app.exec_())




